### ISSUE TITLE
MplusAutomation  runmodel error cannot change working directory

### ISSUE THREAD

**Issue by fadaniya** [michaelhallquist/MplusAutomation#26] opened 2015-08-07 20:47 UTC
Hi
I am using R studio Version 0.99.467  , my r version is 3.2.1  I am using the package Version 
using windows 7

MplusAutomation, the code is 

> runModels("E:/puno/puno_met_paper1/base.inp")

 and the error is: 
Error in setwd(directory) : cannot change working directory

i thought it was a problem with windows not letting me write or make modifications so i tried with no success:
changed the R folder to be able to write files
changed the wd both from rstudio and in r to my project file
run  r studio as  administrator
i also installed and run Reimage Repair  (recommended for r problems in windows)

any ideas how can i solve my issue
thank you
fernando

**Comment by JWiley** [comment] 2015-08-07 23:05
Hi Fernando,

Does this work from within R?

setwd("E:/puno/puno_met_paper1/")

Best,

Josh


On Sat, Aug 8, 2015 at 6:47 AM, fadaniya <notifications@github.com> wrote:

> Hi
> I am using R studio Version 0.99.467 , my r version is 3.2.1 I am using
> the package Version
> using windows 7
>
> MplusAutomation, the code is
>
> runModels("E:/puno/puno_met_paper1/base.inp")
>
> and the error is:
> Error in setwd(directory) : cannot change working directory
>
> i thought it was a problem with windows not letting me write or make
> modifications so i tried with no success:
> changed the R folder to be able to write files
> changed the wd both from rstudio and in r to my project file
> run r studio as administrator
> i also installed and run Reimage Repair (recommended for r problems in
> windows)
>
> any ideas how can i solve my issue
> thank you
> fernando
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michaelhallquist/MplusAutomation/issues/26>.
>



-- 
Joshua F. Wiley, Ph.D.
http://joshuawiley.com/
---
Postdoctoral Research Fellow
Mary MacKillop Institute for Health Research
Australian Catholic University
---
Senior Partner, Elkhart Group Ltd.
http://elkhartgroup.com
Office: 260.673.5518

**Comment by fadaniya** [comment] 2015-08-08 22:14
Hi Josh
Thanks for your prompt replay.
the setwd works  from r and from r studio, i changed the directory but when i run
 runModels("E:/puno/puno_met_paper1/base.inp") i get the same error message regardless of where is the wd

**Comment by michaelhallquist** [comment] 2015-08-10 13:21
Hi Fernando,

The problem is that at the moment, runModels is intended mostly to run several models within a given directory, whereas you have specified a single model. I should probably improve the code a bit to accommodate this circumstance, but for now, you’d want to use the directory where the .inp file resides, along with a filefilter.

runModels(E:/puno/puno_met_paper1”, filefilter=“base.inp”)

(technically, the period in base.inp will be interpreted as a regular expression meaning “any single character”, but that shouldn’t mess things up here)

Hope that helps,
Michael

**Comment by fadaniya** [comment] 2015-08-10 16:44
sounds good, i will try it later, i was just building little by little all modelsthanksfernando

**Comment by michaelhallquist** [comment] 2017-05-22 14:05
In the current development version (which will become CRAN v0.7), the key parameter to runModels() is target, which can be a directory (as before) or a single .inp file.

**Closed by michaelhallquist** 2017-05-22 14:05 UTC
