### ISSUE TITLE
readModels no longer working

### ISSUE THREAD

**Issue by joejonesphd** [michaelhallquist/MplusAutomation#125] opened 2020-07-01 20:46 UTC
A couple of weeks ago, I ran some Mixture models and was using the package to read in the information for all of the models with `readModels()`. Everything worked great. However, now I am getting the following error. 
"The length of the supplied vector is not appropriate to generate the matrix. Please check the data file."
The .out file has not changed and re-running the models with `runModels()` and everything in Mplus is fine. I am just unable to read in the information.

**Comment by cjvanlissa** [comment] 2020-07-02 10:42
Dear Joe Jones, could you please provide a reproducible example?

**Comment by joejonesphd** [comment] 2020-07-02 13:05
I am unable to attach the .out files. But the code is simply

`library(MplusAutomation)
all <- readModels(target = getwd(),
                  recursive = T)`

I then get the error below for every single .out file in the folder. I even try reading it in one at a time and the same error occurs. 

Reading model:  C:/Users/jjones/Desktop/trainingcuttwo_2_class.out 
The length of the supplied vector is not appropriate to generate the matrix. Please check the data file.<simpleError in 1:matSize: argument of length 0>

As I mentioned, this was working a couple of weeks ago. I even tried running it with R 3.5 and 3.6 and receive the same error.

Please let me know if you need any additional information. Thanks

**Comment by michaelhallquist** [comment] 2020-07-02 13:10
Hi there, if you change the extension of the file from .out to .txt, you should be able to upload this. I haven't had any problems with readModels lately, so it's hard to figure out the problem without the exact file that produces it.

Thanks,
Michael

**Comment by joejonesphd** [comment] 2020-07-02 13:17
Thanks Michael, but when I save the .out file to a .txt file and adjust the code to below, I get the following error
all <- readModels(target = "C:/Users/jjones/Desktop/training_2_class - Copy.txt", recursive = F)

Error in getOutFileList(target, recursive, filefilter) : Specified target is not an output file. Target:C:/Users/jjones/Desktop/training_2_class - Copy.txt

**Comment by joejonesphd** [comment] 2020-07-02 13:24
I added some .out files here: https://github.com/joejonesphd/Mplus if that helps

**Comment by joejonesphd** [comment] 2020-07-02 14:08
I uninstalled/reinstalled R, and now it is reading in the output from Mplus like it was before. However, I still get the error about the supplied vector that I never got before.

**Comment by pjugert** [comment] 2020-07-31 19:09
I have a similar problem with `readModels()`  command. I request readModels with the following command:

`results_NI_GER <- readModels(target = "C:/Users/Philipp Jugert/Google Drive/WP7/Identity paper/LTA_final/4-class_lta_ni_ger_novar.out")`

I then get the following error messages:
Error extracting latent class counts in output file: C:/Users/Philipp Jugert/Google Drive/WP7/Identity paper/LTA_final/4-class_lta_ni_ger_novar.out
<simpleError in strsplit(trimws(grep("\\s*Latent Class\\s{2,}", avgProbs, value = TRUE)),     "\\s+", perl = TRUE)[[1]]: Indizierung außerhalb der Grenzen>
Warnmeldungen:
1: In rbind(c("A_NI1", "3.551", "0.087", "40.721", "0.000"), c("A_NI2",  :
  number of columns of result is not a multiple of vector length (arg 1)
2: In detectColumnNames(filename, modelSection, sectionType) :
  Unable to determine column names for section model_results.
  C:/Users/Philipp Jugert/Google Drive/WP7/Identity paper/LTA_final/4-class_lta_ni_ger_novar.out
3: In rbind(c("A_NI1", "3.326", "3.380", "3.407", "3.551", "3.694",  :
  number of columns of result is not a multiple of vector length (arg 11)

I am attaching the output file associated with this error message
[4-class_lta_ni_ger_novar.txt](https://github.com/michaelhallquist/MplusAutomation/files/5008640/4-class_lta_ni_ger_novar.txt)

**Comment by michaelhallquist** [comment] 2020-10-11 18:22
Hi there, @pjugert, I have verified that your output file parses as expected using the development version of the package on Github. It still throws an objection to the R-SQUARE section, but that is valid since the section is empty. @joejonesphd, I couldn't access the link above, so couldn't verify your problem, but feel free to upload the offending .out here (with .txt suffix -- it's fine, I'll rename it after download) and I can check. For now, I'm closing this since it seems like both specific issues are resolved. Feel free to reopen it if you have a reproducible example that still throws an error.

Michael

**Closed by michaelhallquist** 2020-10-11 18:22 UTC
