### ISSUE TITLE
digest dependency fails on install in dev version

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#42] opened 2017-02-08 13:26 UTC
This relates to development version. Very clever with the md5 hash from digest, I forgot that option. Unfortunately I am not able to install the latest version as I continually get an error with the 'digest' dependency. Tried RGui and RStudio). Works fine to install digest independently, but then it is removed when MplusAutomation fails. (Possible for me to not install digest when installing, just for testing?)

```
> install.packages("digest")
Installing package into ‘M:/pc/Dokumenter/R/win-library’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/digest_0.6.12.zip'
Content type 'application/zip' length 170307 bytes (166 KB)
downloaded 166 KB

package ‘digest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\stephd\AppData\Local\Temp\RtmpCgL0Np\downloaded_packages
> library(devtools)
> install_github("michaelhallquist/MplusAutomation")
Downloading GitHub repo michaelhallquist/MplusAutomation@master
from URL https://api.github.com/repos/michaelhallquist/MplusAutomation/zipball/master
Installing MplusAutomation
Installing 1 package: coda
Installing package into ‘M:/pc/Dokumenter/R/win-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/coda_0.19-1.zip'
Content type 'application/zip' length 201696 bytes (196 KB)
downloaded 196 KB

package ‘coda’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\stephd\AppData\Local\Temp\RtmpCgL0Np\downloaded_packages
Installing 1 package: digest
Installing package into ‘M:/pc/Dokumenter/R/win-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/digest_0.6.12.zip'
Content type 'application/zip' length 170307 bytes (166 KB)
downloaded 166 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

The downloaded binary packages are in
        C:\Users\stephd\AppData\Local\Temp\RtmpCgL0Np\downloaded_packages

[truncated package installation that works fine]

The downloaded binary packages are in
        C:\Users\stephd\AppData\Local\Temp\RtmpCgL0Np\downloaded_packages
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/stephd/AppData/Local/Temp/RtmpCgL0Np/devtools2ed430017f92/michaelhallquist-MplusAutomation-7b53a98"  \
  --library="M:/pc/Dokumenter/R/win-library" --install-tests 

ERROR: dependency 'digest' is not available for package 'MplusAutomation'
* removing 'M:/pc/Dokumenter/R/win-library/MplusAutomation'
Error: Command failed (1)
> 
```

**Comment by JWiley** [comment] 2017-02-08 22:25
Unfortunately I do not think it will be easy to install and test without digest.  From the errors, it loos like the issue is that is cannot remove the prior installation of digest.  I think I've had similar problems when a package was already loaded or something like that.  Can you try installing from a clean R session with no packages loaded?

Alternately, you can download this tar ball and use `install.packages()` on it
[MplusAutomation_0.6-4.tar.gz](https://github.com/michaelhallquist/MplusAutomation/files/762108/MplusAutomation_0.6-4.tar.gz)

Again I would run the install from a clean R session without (extra) packages loaded.

**Comment by JWiley** [comment] 2017-05-23 13:54
@sda030 Just checking in on this again.  Are you still have issues with MplusAutomation or can this issue be closed?

**Comment by sda030** [comment] 2017-05-23 14:23
Still fails. Research project moved on so I found some manual solutions. Unfortunately no time to debug... Great package though!

**Comment by JWiley** [comment] 2017-05-24 13:40
Okay I am closing for now as it seems to be more related to the installation of the digest package than MplusAutomation and I cannot reproduce on Windows 10 or Mac OS that I have access to.  Feel free to reach out in the future if you have time to dig into what's going on.

**Closed by JWiley** 2017-05-24 13:40 UTC
