### ISSUE TITLE
Warning: "closing unused connection <connection_number> (<file_route>)" in readModels()

### ISSUE THREAD

**Issue by DaniMori** [michaelhallquist/MplusAutomation#47] opened 2017-05-17 16:52 UTC
The "scan" function opens a connection but it's never properly closed, thus generating a warning when the garbage collector destroys the pointer to that connection and it is closed by R.

Among other solutions, one suggestion would be, in line 66 of parseOutput.R:

```R
fileconn <- file(curfile) # Add this line
outfiletext <- scan(fileconn, what="character", sep="\n", strip.white=FALSE, blank.lines.skip=FALSE, quiet=TRUE) # Change 'curfile' to 'fileconn' here

allFiles[[listID]]$input <- inp <- extractInput_1file(outfiletext, curfile)
warn_err <- extractWarningsErrors_1file(outfiletext, curfile, input=inp)
allFiles[[listID]]$warnings <- warn_err$warnings
allFiles[[listID]]$errors <- warn_err$errors
allFiles[[listID]]$summaries <- extractSummaries_1file(outfiletext, curfile, input=inp)
allFiles[[listID]]$parameters <- extractParameters_1file(outfiletext, curfile)
allFiles[[listID]]$class_counts <- extractClassCounts(outfiletext, curfile, allFiles[[listID]]$summaries) #latent class counts
allFiles[[listID]]$mod_indices <- extractModIndices_1file(outfiletext, curfile)
allFiles[[listID]]$savedata_info <- fileInfo <- l_getSavedata_Fileinfo(curfile, outfiletext, allFiles[[listID]]$summaries)

#missing widths indicative of MI/MC run
if (!is.null(fileInfo) && is.na(fileInfo[["fileVarWidths"]])) {
  allFiles[[listID]]$savedata <- l_getSavedata_readRawFile(curfile, outfiletext, format="free", fileName=fileInfo[["fileName"]], varNames=fileInfo[["fileVarNames"]], input=inp)
} else {
  allFiles[[listID]]$savedata <- l_getSavedata_readRawFile(curfile, outfiletext, format="fixed", fileName=fileInfo[["fileName"]], varNames=fileInfo[["fileVarNames"]], varWidths=fileInfo[["fileVarWidths"]], input=inp)
}

allFiles[[listID]]$bparameters <- l_getSavedata_Bparams(curfile, outfiletext, fileInfo, discardBurnin=FALSE)
allFiles[[listID]]$residuals <- extractResiduals(outfiletext, curfile)
allFiles[[listID]]$tech1 <- extractTech1(outfiletext, curfile) #parameter specification
allFiles[[listID]]$tech3 <- extractTech3(outfiletext, fileInfo, curfile) #covariance/correlation matrix of parameter estimates
allFiles[[listID]]$tech4 <- extractTech4(outfiletext, curfile) #latent means
allFiles[[listID]]$tech7 <- extractTech7(outfiletext, curfile) #sample stats for each class
allFiles[[listID]]$tech9 <- extractTech9(outfiletext, curfile) #tech 9 output (errors and warnings for Monte Carlo output)
allFiles[[listID]]$tech12 <- extractTech12(outfiletext, curfile) #observed versus estimated sample stats for TYPE=MIXTURE
allFiles[[listID]]$fac_score_stats <- extractFacScoreStats(outfiletext, curfile) #factor scores mean, cov, corr assoc with PLOT3

#allFiles[[listID]]$indirect <- extractIndirect(outfiletext, curfile) #MODEL INDIRECT output (in progress)

#aux(e) means and pairwise comparisons
allFiles[[listID]]$lcCondMeans <- extractAux(outfiletext, curfile)

close(curfile) # Add this line
```

It could be even further improved if all lines from 66 to 98 were inside a `tryCatch()` function, with the `close(curfile)` line in the `finally` argument.

**Comment by michaelhallquist** [comment] 2017-07-12 13:41
Hi Dani,

Thanks for letting us know about this warning. I've tried to replicate it on my end, but have not been able to produce the warning you noted. Would you be able to send an example file and command that generates the warning? To my knowledge, scan does not require the user to close a connection if the file argument is a string pointing to a file. But it's quite possible that I'm wrong and am happy to update the readModels code along the lines you suggest if I can reproduce the problem so I can verify the fix.

Thanks,
Michael

**Comment by michaelhallquist** [comment] 2017-10-22 01:10
Closing this for now since I cannot reproduce and don't have access to a reproducible example.

**Closed by michaelhallquist** 2017-10-22 01:10 UTC
